# Generated by Django 3.2 on 2021-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes_configuration', '0002_alter_scrapetarget_last_scraped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapetarget',
            old_name='last_scraped',
            new_name='last_enqueued_at',
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='last_scraped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
